# Generated by Django 4.2.6 on 2023-11-02 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('Address', models.TextField()),
                ('last_visited', models.DateField(auto_now_add=True)),
                ('country', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('Address', models.TextField()),
                ('last_visited', models.DateField(auto_now_add=True)),
                ('country', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Teach_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Exam_name', models.CharField(max_length=20)),
                ('Maxscore', models.IntegerField()),
                ('started', models.DateTimeField()),
                ('length', models.TimeField()),
                ('course', models.CharField(max_length=10)),
                ('tid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Teach_course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=10)),
                ('tid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Stud_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Exam_name', models.CharField(max_length=20)),
                ('Score', models.IntegerField()),
                ('started', models.DateTimeField()),
                ('ended', models.DateTimeField()),
                ('Examid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teach_history')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
            ],
        ),
    ]
